### ISSUE TITLE
What is the idiomatic way to import and use the `Error` type?

### ISSUE THREAD

**Issue by matklad** [rust-lang-nursery/failure#155]
Hi!

I see two ways of using `Error`:

- qualified, `failure::Error`,
- unqualified, `Error`.

which one is preferred? The short one is short, but it might conflict with `std::error::Error`, and with `my_lib::Error`.

**Comment by withoutboats** [comment]
I prefer an unqualified import, not using `std::error::Error` anymore, and not naming your own erorr types `Error`. I don't know what other people do. :-)

**Comment by matklad** [comment]
Hm, the last point is interesting! I think the API guidelines at least at one point suggested to prefer `foo::Error` over `FooError`, and it's definitely true that serde suggest `format::Error`, and that stdlib uses `io::Error`.

So it would be nice to have some canonical pattern to deal with clashing names. I don't think this is an actionable item though :( Perhaps people from the libs team could give some advice?

**Comment by xoac** [comment]
@matklad I will just add a link to your post https://doc.rust-lang.org/1.0.0/style/style/naming/README.html#avoid-redundant-prefixes-[rfc-356] there is more information how to write in rust.

**Comment by mitsuhiko** [comment]
I'm closing this for now and going to leave this undecided for now. If it turns out the std error type is being resolved I would propose to rename `failure::Error` to something else.

**Comment by dekellum** [comment]
FWIW, at the closing point for this, I've been using this

``` rust
/// Convenient and non-repetitive alias.
/// Also: "a sudden brief burst of bright flame or light."
use failure::Error as Flare;
```
This *could* be made a `pub use` export from the *failure* crate, with same docs, and I'd be thankful.
