### ISSUE TITLE
The Error's backtrace ought to be an Option

### ISSUE THREAD

**Issue by otavio** [rust-lang-nursery/failure#162]
Allowing to check:

```rust
if err.backtrace().is_some() {
    ...
}
```

To decide about printing the backtrace or not, is more idiomatic no? for now, I need to check if RUST_BACKTRACE is set.

**Comment by withoutboats** [comment]
What's wrong with printing it unconditionally? It's not an option because in `Fail`, the optionality is connected to whether this error type has a backtrace, not whether or not `RUST_BACKTRACE` is set. I just figured you'd always print it and it'd print nothing if backtraces are turned off.

**Comment by Celti** [comment]
In my case, I print errors — and backtraces — with `log` macros, which add timestamps and such to the print. If backtraces are disabled I get a line like `ERROR 2018-02-12T22:07:45Z: main_app ` with no backtrace info attached to it.

**Comment by withoutboats** [comment]
That's annoying.

Currently there's a private `is_none` method on Backtrace. Maybe we could expose that (probably under a different name).

**Comment by otavio** [comment]
I'd use `is_empty` so it is idiomatic.
