### ISSUE TITLE
feature flags not forwarded to failure_derive on 0.1.1

### ISSUE THREAD

**Issue by mammothbane** [rust-lang-nursery/failure#171]
Can't compile for `no_std` on 0.1.1 while using `#[derive(Fail)]`:

```
error[E0433]: failed to resolve. Maybe a missing `extern crate std;`?
 --> src/lib.rs:5:30
  |
5 | #[derive(Debug, Clone, Copy, Fail)]
  |                              ^^^^ Maybe a missing `extern crate std;`?
```

with this `Cargo.toml`:

```
[package]
name = "failure-nostd-breaks"
version = "0.1.0"

[dependencies.failure]
version = "0.1.1"
default-features = false
features = ["derive"]
```

The current `Cargo.toml` for `failure` has the following section for `failure_derive`:

```
[dependencies.failure_derive]
version = "0.1.1"
optional = true
```

which is conspicuously missing a `default-features = false`, meaning that generated code always uses `::std` regardless of the features enabled on `failure`. Compiles fine with a local patch of `failure` with that one line added.

I'd submit a PR, but I'm not sure how the compat/shimming works exactly.

**Comment by withoutboats** [comment]
This should be fixed for the next release! Sorry about that :(

**Comment by withoutboats** [comment]
Actually, if you wanted to add a test to `failure-1.X/tests` which attempted to derive Fail on no_std, it would be a great addition :)
