### ISSUE TITLE
What is the best way to deal with error data that cannot be `Send`?

### ISSUE THREAD

**Issue by ubolonton** [rust-lang-nursery/failure#173]
This comes up when I try integrating Rust with Emacs Lisp. When calling Lisp, the returned errors contain Lisp objects wrapped in a `Value` type. The objects can be GC'ed later on, and can only be safely accessed during the lifetime of a temporary `Env`, which encloses the call to Rust. Therefore the values are lifetime-bound by `Env`. `Env` itself is not `Sync`, so `Value<e>` cannot be `Send`. To be able to carry them in a `failure`-compatible error type, I could think of 2 ways:

- Create another wrapper `OwnedValue`, with a constructor that increases the ref count of the underlying Lisp object to protect it from being GC'ed, and a `Drop` that decreases the ref count. This is wasteful when the Rust code just wants to propagate the error back to Lisp, without any inspection.
- Create another wrapper `TempValue`. Mark this type as `Send+Sync`, then mark all its methods as `unsafe`, so Rust code that attempts to inspect the error has to follow a safety contract. This is what I went with.

What is the recommended way to deal with situations like this?

**Comment by withoutboats** [comment]
This sounds like it might just not be a good use case for failure. Do you have a particular use for these errors to implement `Fail`, or is just because they're error types so it seems right?

**Comment by withoutboats** [comment]
I looked through your repo, saw that its a library - so you don't know what an end user wants to do with those errors.

What if you had one type that was cheap but does not implement Fail, and it implements a conversion into another type that is Send + Sync, at the cost you mentioned?

**Comment by ubolonton** [comment]
My lib deals with 3 categories of error:
1. An error type that a user-defined function must return, if it is to be exported to Lisp.
2. An error type that the lib returns when calling Lisp.
3. Error types coming from user code, or other crates. Most of the time these type would implement `failure::Fail`, or standard `error::Error`.

My requirements are:
- Converting from 2/3 to 1 should be easy.
- User code can inspect 2, but most of the time it should be converted to 1 (propagating errors, letting higher-level (Lisp) code handle them), so 2->1 conversion should be cheap.

For 1, I used `failure::Error`, for its backtrace support, and its blanket `From` for 3->1. To make 2->1 cheap, I made 2 implement `Fail`.

Making 2 non-`Fail` and keeping 2->1 cheap means 1 cannot be `failure::Error`. I guess that means it's probably better to use custom non-`Fail` types for both 1 and 2?

**Comment by dathinab** [comment]
I have been thinking about how to make `failure` usable with a wider range of errors (sadly I found quite a large number of Errors which do not play nicely with `failure` and sometimes they are  not compatible at all).

My latest idea was to have a less constraint/more general trait and base `Fail` on it, I will call
it `GeneralFail` here. While this trait can be implemented for more types it's less ergonomic as
e.g. any `Send`/`Sync`/`'static` bounds have to be passed around manually. The trait would
be something like:

```rust
pub trait GeneralFail {
    fn backtrace(&self) -> Option<&Backtrace> { None }

    fn cause<'a, 'b: 'a>(&self) -> Option<&'a (GeneralFail + 'b)>
        where Self: 'b;

    // context and other helper methods ommited
}
```

The special think here is the (ugly) signature of `cause` it will have the effect, that
the returned reference to a trait-object lives at last as long self. I.e. if `Self: 'static`
then it can return `&(GeneralFail + 'static)` which can be casted. (Note that it can
also return any shorter lifetime which lives at last as long a `'a`).

Yay, we now have a better `std::error::Error` type, but when we extend it to
`Fail` and it's `Send` + `Sync` bound it get's slightly troublesome.

One approach to then implement `Fail` on `GeneralFail` is following:

```rust
trait Fail: GeneralFail + Send + Sync + 'static {}

impl<T> Fail for T where T: GeneralFail + Send + Sync + 'static {}
```

This is the most straight forward approach, but has a number of drawbacks:

1. to use any method attached to `GeneralFail` (`cause`/`backtrace`) it is
     required to import `GeneralFail` _additionally_ to `Fail`
2. `cause` returns a `GeneralFail` while it keeps `'static` and therefore allows
    casting it will not propagate `Send`+`Sync`, given how `cause` is used and
    that a reference is returned and that scoped threads are uncommon I think
    it's not a big problem in this case but it's still there
   - this interestingly has the effect, that a type implementing `Fail` can have a
     cause which is only `Send` but not `Sync`
3. well the `cause` signature is ugly, but then it also allows people to learn about
    rust ;=)

As a side not while the derive impl. has to be changed it's interface does not
need to change it will just generate an additional `GeneralFail` impl, through
a alternative `derive(GeneralFail)` should be added to (can `GeneralFail` use
`fail` attributes like e.g. `#[fail(display = "...")]`, I haven't really written any
proc-derives until now)

---

I also considered `Fail` having the same signature as it has now (plus the `Fail: GeneralFail` constraint), but then thinks will get annoying wrt. the implementation of `cause`. It would require a "cast" from `&Fail` to
`&GeneralFail` which currently isn't really supported by rust (but probably could maybe be in the future). 

Through to prevent requiring importing both `Fail` and `GeneralFail` a `cause`/`backtrace` implementation could be added to `Fail` still `cause` would return `Option<&(GeneralFail+'static)>` so if you abstract over
it you would need to use `GeneralFail` as type in which case `err.cause` can no longer be used as it would
be ambiguous so this isn't really an option.

**Comment by mitsuhiko** [comment]
For now I would propose to point people towards [fragile](https://docs.rs/fragile) for issues with `Send`. I know it's not great but I do not want to change the builds at the moment.
