### ISSUE TITLE
The small-error feature never drops value

### ISSUE THREAD

**Issue by seanmonstar** [rust-lang-nursery/failure#180]
With the `small-error` feature turned on, any value that `Error` wraps never has its destructor called.

```rust
struct LeakMe;

impl Fail for LeakMe {}

impl Drop for LeakMe {
    fn drop(&mut self) {
        println!("LeakMe dropped");
    }
}

fn main() {
    let val = LeakMe;
    // comment out next line to see correct behavior
    let _err = Error::from(val);
    // "LeakMe dropped" is never printed
}
```

While the heap allocation of the trait object is deallocated, its possible for the value to itself have pointers to data that needs to be freed when dropped.

**Comment by withoutboats** [comment]
Oof, you're completely right. :-\ I remember implementing this, but it was probably in one of the branches I worked on before the one that become the actual implementation. I'll put a PR up soon.

**Comment by mitsuhiko** [comment]
This has been closed by removing the feature.
