### ISSUE TITLE
Show example of traversing the chain of causes

### ISSUE THREAD

**Issue by pachi** [rust-lang-nursery/failure#185]
I've found Failure's docs very nice, but there are some areas that I found a bit difficult to discover while learning how to migrate to Failure from bare "error handling" (using panics and unwrap()).

One of these things I would like to have found earlier is an example showing how to display a chain of causes:

```
let value = match get_value(params) {
        Ok(value) => value,
        Err(e) => {
            eprintln!("Error: {}", e);
            for e in e.causes().skip(1) {
                eprintln!("Due to: {}", e);
            }
            exit(1);
        }
    };
```

Also, it would be useful to have an example of switching from the standard ```Error``` to a ```Failure::Error``` together with ```.context("message")?```, ```.context(format!("Message with value {}", value)?``` or ```Err(format_err!("Message with {}", value))```

**Comment by otavio** [comment]
Same here; I missed this information as well.

**Comment by mitsuhiko** [comment]
Going to close this as it's in the book already.
