### ISSUE TITLE
Custom fail type does not implement failure::Fail

### ISSUE THREAD

**Issue by Bert-Proesmans** [rust-lang-nursery/failure#194]
Hi guys,

Like the title implicates I'm fighting with the compiler. To understand what exactly I mean there is a reproduction here: https://github.com/Bert-Proesmans/failure_issue.
I'm running rustc 1.27.0-nightly (056f589fb 2018-04-07).

I suppose i'm not understanding something, because this example is so simple it shouldn't be possible to NOT get it to compile.
I would appreciate if someone in here would point out my mistake. Thank you

**Comment by untitaker** [comment]
The type parameter seems to be the problem. Hardcoding ID to be usize works, for example.

I think this is a bug in failure, but I am also not sure if having error types with type params is good for ergonomics.
