### ISSUE TITLE
#[derive(Fail)] assumes std exists

### ISSUE THREAD

**Issue by xfix** [rust-lang-nursery/failure#214]
This isn't the case for `#[no_std]` libraries. This can be dealt with by making `failure` export an undocumented `core` (something like `#[doc(hidden)] pub use core`). Or it could be documented that an user needs to use `use core as std` in such libraries.

**Comment by xfix** [comment]
Okay, I see, the issue is that you need to disable `std` feature for `failure_derive`. You cannot really disable `std` feature however if some other crate within the same build enables this feature.

**Comment by mitsuhiko** [comment]
This is fixed in master now.
