### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by alexreg** [rust-lang-nursery/failure#217]
1. Is there a reason the homepage on crates.io is still @withoutboats's fork rather than this official version?

2. Why have there been no releases in the last 6 months? If I want to use failure, should I target the Git repo?

**Comment by mulkieran** [comment]
Related: #218 .

**Comment by alexreg** [comment]
@withoutboats Maybe you could kindly answer the second question? :-)

**Comment by mitsuhiko** [comment]
@alexreg i'm preparing a release but i need to wait for @withoutboats to give me crates.io access.

**Comment by alexreg** [comment]
@mitsuhiko Thanks for the update. Look forward to it, as *failure* is definitely the best-architected error lib for Rust around.
