### ISSUE TITLE
new `crate` keyword breaks derive

### ISSUE THREAD

**Issue by kazcw** [rust-lang-nursery/failure#225]
This panics ("failed to parse derive input"):

    #[derive(Fail)]                                                                                                  
    crate struct Foo;

This works:

    #[derive(Fail)]                                                                                                  
    pub(crate) struct Foo;

**Comment by dtolnay** [comment]
I believe the fix will be to upgrade to a newer version of Syn which supports this newer syntax.

**Comment by ExpHP** [comment]
This has become more relevant now with the recent [call to arms](https://internals.rust-lang.org/t/help-test-out-the-2018-module-system-changes/8047) to test the module system

**Comment by ExpHP** [comment]
Ah, I think I see what's going on.  This has been fixed, but the fix is not released because the next planned update to 0.1.X was to have it use a compatibility shim over 1.0.0 (which got delayed).

This is a shame; perhaps some recent fixes like this one should be backported onto something more closely resembling the 0.1.1 release.

**Comment by alexcrichton** [comment]
@mitsuhiko was curious, do you know if there's a plan for releasing failure 0.1.2 with a fix like this?

**Comment by mitsuhiko** [comment]
@alexcrichton yes, but i do not yet have rights to crates.io

**Comment by mitsuhiko** [comment]
I'm going to see if I can downgrade the current master so it does not need the 1.0 version, otherwise I might just fork it off from an older revision for now.

**Comment by alexcrichton** [comment]
@withoutboats ping on this, mind giving @mitsuhiko publish rights?

**Comment by mitsuhiko** [comment]
There is a pending release in #229 now. I need to do a lot of testing though (ideally a crater run but I do not know how to achieve that) as it's a merged version of 0.1 and 1.0.

**Comment by mitsuhiko** [comment]
This is fixed on master. I'm going to close this issue for now.
