### ISSUE TITLE
impl std::error::Error

### ISSUE THREAD

**Issue by aep** [rust-lang-nursery/failure#240]
why does failure::Error not implement std::error::Error ? this makes it rather annoying to use with libraries that don't use failure.

in my case:

```
Deadline::new(something_that_returns_failure, ....)
.map_err(|e|Error::from(e))
.and_then(move |rq|{
     return Err(Failure...



176 |                     .map_err(|e|Error::from(e))
    |                                 ^^^^^^^^^^^ the trait `std::error::Error` is not implemented for `failure::Error

```

**Comment by matklad** [comment]
That's not possible b/c there's an `impl<T: ::std::error::Eror> Fail for E`. If you add an impl in the opposite direction, you'll get overlapping impls. 

There's `compat` method, which you are probably looking for: https://docs.rs/failure/0.1.2/failure/trait.Fail.html#method.compat

**Comment by aep** [comment]
Thanks, got it
