### ISSUE TITLE
Different compiler versions disagree on whether failure_derive macro is used or not

### ISSUE THREAD

**Issue by mulkieran** [rust-lang-nursery/failure#278]
This leads to some compatibility issues. The code I have now compiles on 1.25.0 and 1.28.0 but reports an unused ```[macro_use]``` import for 1.31.0. https://travis-ci.org/stratis-storage/devicemapper-rs/jobs/466549505. Is this a bug in Rust, or something about the behavior of the ```failure_derive``` crate?

**Comment by mitsuhiko** [comment]
Going to close this. I think this might be because you are using `failure_derive` directly which is not intended.
