### ISSUE TITLE
Build failure with backtrace 0.3.10

### ISSUE THREAD

**Issue by mpapierski** [rust-lang-nursery/failure#281]
Hello,

Today backtrace crate got 0.3.10 release and apparently it introduces a regression - I can't build `failure v0.1.3` anymore in my crate because `cargo` resolved `backtrace` to `0.3.10`. See alexcrichton/backtrace-rs#134 for more details.

I'm not yet sure if its a planned regression and failure needs to be updated to accomodate changes (probably more crates can be affected by that).

**Comment by BurntSushi** [comment]
See https://github.com/rust-lang-nursery/failure/pull/279, https://github.com/rust-lang-nursery/failure/issues/280

**Comment by mpapierski** [comment]
@BurntSushi Thanks! That was fast. I'm open for closing this one, but I'd keep it for a while for better visibility for awhile.

**Comment by mitsuhiko** [comment]
Closing this as master would be compatible with this.
