### ISSUE TITLE
No method iter_chain() is defined for Context<T>

### ISSUE THREAD

**Issue by vimmerru** [rust-lang-nursery/failure#286]
Hi, i am trying to use `iter_chain()` for `Context<T>` and compiler says that no such method defined. May be it is because it only exists in `impl` block of `Fail` and isn't defined in `pub trait` statement. 

I still can use `causes()`, but it produces deprecation warning.

Any help with this?

**Comment by mitsuhiko** [comment]
Works for me:

```rust
extern crate failure;

use failure::Fail;
use std::io;


fn main() {
    let err = io::Error::new(io::ErrorKind::Other, "This is an error");
    let err_with_ctx = err.context("Testing");
    for cause in Fail::iter_chain(&err_with_ctx) {
        println!("{}", cause);
    }
}
```

**Comment by rasa200** [comment]
Hi there! 

Would it be possible to add such an example in the documentation, please?
I also didn't understand it at the beginning.


Thanks beforehand!
